### ISSUE TITLE
Cannot use game constants in tests

### ISSUE THREAD

**Issue by urxvtcd** [screepers/screeps-typescript-starter#126]
Hi guise! Right after fresh cloning, when I go to unit tests and add a simple assertion like
```javascript
assert.equal(CREEP_LIFE_TIME, 1500);
```
I get an error, because this constant is not defined. Am I missing something? How do I fix that?

**Comment by eduter** [comment]
It's been a long time since I tried using the starter kit for testing, so I don't remember what problems I've had. Maybe that was one of them. I ended up forking it and setting it up with Jest. If you're serious about unit testing, I recommend you use my fork:

https://github.com/eduter/screeps-typescript-jest-starter

**Comment by urxvtcd** [comment]
Oh, that's great, I'll try it. Truth to be told I felt overwhelmed by this starter, tried to roll my own minimal one, and failed, because of JavaScript's byzantine ways, haha. Thanks, a lot!
