### ISSUE TITLE
Support for Node.JS v14

### ISSUE THREAD

**Issue by eikowagenknecht** [screepers/screeps-typescript-starter#151]
Running the setup tutorial I get the following message:
![image](https://user-images.githubusercontent.com/1475672/103305575-c54a2b00-4a0b-11eb-893d-8306466125b9.png)

Seems like there are quite a few outdated version references:
![image](https://user-images.githubusercontent.com/1475672/103305599-d430dd80-4a0b-11eb-9b1a-573065f0a61b.png)

Can those just be set to the newest versions in package.json?

**Comment by bastianh** [comment]
you can edit the values in package.json and see if everything works with newer node / package versions... if everything works you could create a pull request.

you should not update @types/lodash since this should be the version that is used on the screeps server.

personally I use Volta (https://volta.sh) to run specific node versions for different projects.

**Comment by djD-REK** [comment]
There's a problem with Screeps and node-gyp on Windows in versions 14, but
10 and 12 work. I use nvm for version management, but I think the official
Screeps package still uses Node 10.

**Comment by scottw-kr** [comment]
Looks like this (https://github.com/screepers/screeps-typescript-starter/commit/26be47f5f45ff708d8c664fdb960ea78cc030891) may cover your second concern. The node version may not be something they can change. It looks like screeps proper uses node 8 || 10 

![Screen Shot 2021-08-25 at 11 51 34 AM](https://user-images.githubusercontent.com/80055821/130823401-f858a30d-7b27-44e1-b0fe-a5166c7be90a.png)
