### ISSUE TITLE
Look into using Webpack's watch mode

### ISSUE THREAD

**Issue by resir014** [screepers/screeps-typescript-starter#36]
As mentioned by @bastianh on #33, switching from using gulp's watch to webpack's watch may improve overall build performance.

**Comment by bastianh** [comment]
I'm sometimes working on an older computer without ssd, and there it is a huge improvement. My current test setup has some drawbacks, so it's not worth sharing. 
I currently use gulp only to watch the `dist` directory to upload and use webpack with watch to compile.
Instead of `ts-loader` I'm using `awesome-typescript-loader`... the drawback here is that it compiles code and checks types in a different process... so it might upload broken code which is not that bad for me because I develop on a testserver most of the time. I don't have to wait for the typechecks because I'm using webstorm for that anyways.

ok .. but here some numbers on that 2010 computer I sometimes have to use ;)

initial compiling of project with webpack: 4251ms
recompile from watch when changing a file:  472ms

that's really a huge differerence ;)

**Comment by resir014** [comment]
> Instead of `ts-loader` I'm using `awesome-typescript-loader`... the drawback here is that
> it compiles code and checks types in a different process... so it might upload broken
> code which is not that bad for me because I develop on a testserver most of the time

@bastianh Hmm. As much of a large performance change it gives, not sure if I want to sacrifice type checking for it. Do you think it's possible to do so in the standard `ts-loader`?

**Comment by bastianh** [comment]
should be no problem .. the challenge is that with webpack watch mode webpack will not return to gulp .. it will continue running and watching so I guess it needs larger changes to the build system

**Comment by bryanbecker** [comment]
I think this can be closed now

**Comment by resir014** [comment]
Yep, closing now.
