### ISSUE TITLE
We need to choose a license for the repository

### ISSUE THREAD

**Issue by bryanbecker** [screepers/screeps-typescript-starter#54]
@screepers/typescript 

Considering OCS is up in arms about copyright on their repo, I think we should add a license here and be done with it.  (Actually, I think we should do that regardless of what OCS is doing)

https://choosealicense.com/  This site makes it easy.

My recommendation is either:

- [MIT license](https://choosealicense.com/licenses/mit/) which basically lets people do whatever they want with the code as long as they attribute the original repo

- [Unlicense](https://choosealicense.com/licenses/unlicense/) which relinquishes all rights

I don't think anyone here cares about retaining rights to this repo, which I why I vote for permissive.

If no one has objections to this, after a few days I'll submit a PR with the UNLICENSE

**Comment by resir014** [comment]
+1 for the Unlicense. I originally planned this to be public domain anyway,
and not having a license file available would probably not reflect that
well.

**Comment by kotarou** [comment]
I'll add my support for Unlicense. Otherwise, I would support the beerware license;
/*
 * ----------------------------------------------------------------------------
 * "THE BEER-WARE LICENSE" (Revision 42):
 * <phk@FreeBSD.ORG> wrote this file.  As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy me a beer in return. 
 * ----------------------------------------------------------------------------
 */

**Comment by resir014** [comment]
Alright, it seems like we have unanimous support for the Unlicense. I'll go add that now.
