### ISSUE TITLE
Which typings do we want to use?

### ISSUE THREAD

**Issue by bryanbecker** [screepers/screeps-typescript-starter#59]
Do we want to stick with the old ones, or migrate to https://github.com/screepers/typed-screeps ?

**Comment by resir014** [comment]
Let's ask for general consensus on the #typescript Slack channel first, then we'll pick what the majority of people want. Personally I prefer the newer `typed-screeps` typings.

**Comment by bastianh** [comment]
I migrated to the new typings and lever looked back ;)

**Comment by resir014** [comment]
Alright, I'll wait for a few more days. If there's no more objections, then I'll create a PR to switch to the new typings.

**Comment by resir014** [comment]
Since we've already long past the time limit for feedback (and the general sentiment on the #typescript Slack channel seems to gravitate towards `typed-screeps` anyway), I'm going to transfer the codebase over to typed-screeps later today.

Other than that, I'll also introduce a slimmer starter code.
