### ISSUE TITLE
Debugging easier on local private server?

### ISSUE THREAD

**Issue by KarateSnoopy** [screepers/screeps-typescript-starter#66]
Thanks a lot for this project.  It's a been great time saver

Can you explain what you mean by this line:
https://github.com/screepers/screeps-typescript-starter/blob/master/config/config.local.ts#L11

I understand how to symlink and what that does, but which folders should I symlink?
1) "/home/USER_NAME/.config/Screeps/scripts/127_0_0_1___21025/default/" (which I'll change to point to the folder where local server wants the files") 
2) and which other one?

And then what benefit does this get me?  I thought with Screeps debugging all you get is logging anyway.

Thanks

**Comment by resir014** [comment]
Hey @KarateSnoopy,

The Screeps Steam client uses a "deploy directory" on your system where it will automatically upload your code to the local/remote server every time you make changes to the code inside that directory.

* On Unix systems, your Screeps deploy dir is located at `$HOME/.config/Screeps/scripts/<domain_name>/<branch>/`.
* I forgot where it is on Windows, and I can't check right now as I'm at work.

The <domain_name> folder name format is always as follows: `domain_tld__port` or `0_0_0_0__port` if it's an IP address.

To use the symlink workflow you can go to `config.local.ts` configure the output `localPath` as follows:

```ts
const localPath = path.join(__dirname, "../dist/local");
```

This will output the built source to `./dist/local` in your project directory, which you can symlink your local deploy directory to it!

```bash
$ sudo ln -s $HOME/.config/Screeps/scripts/<domain_name>/<branch>/ ./dist/local
```

It's much easier when you can run `npm run watch-local` too since changes are automatically saved as you save your code.

Hope that answers your question!

**Comment by ezolenko** [comment]
There is also [screeps-user-script-debug-mod](https://www.npmjs.com/package/screeps-user-script-debug-mod) for actual debugging.
