### ISSUE TITLE
Unable to rollup to own server

### ISSUE THREAD

**Issue by Hekman** [screepers/screeps-typescript-starter#76]
Currently experimenting with the typescript starter (v3.0) and tried to push to the local server on my Mac. However, I am getting the following error:
`(node:80116) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot POST /api/auth/signin`

I have been experimenting with the config file `screeps.json` and I am using the username as I entered on the server and no password. Tried the IP adress, changed it to localhost etc etc:

`  "pserver": {
    "email": "username",
    "password": "",
    "protocol": "http",
    "hostname": "localhost",
    "port": 21025,
    "path": "/",
    "branch": "default"
  }`

Any idea? What am I missing?

**Comment by dmarcuse** [comment]
Do you have [screepsmod-auth](https://github.com/ScreepsMods/screepsmod-auth) installed and a password set for it?

**Comment by Hekman** [comment]
Thanks for the reply! Currently trying to install screepsmod-auth but strangely enough the server is not picking up the mod. When I change the `mods.json` it changes back to the original file without the auth mod. Annoying but a fun puzzle. Will get back on this :)

**Comment by Hekman** [comment]
This did the trick! Thank you!

**Comment by caleywoods** [comment]
### Update 2
I now have this working, accessing the web GUI for screepsmod-auth worked, it's URL is (for me) `http://127.0.0.1/authmod/password/` where I configured a password and signed in through Steam. Once I setup `screeps.json` with my email and password the `Not Authorized!` error went away. 

Note for anyone who may run into this: The email in `screeps.json` is the email associated with my screeps account, not my steam email (they're different since my steam account is ancient).

### Update
I got the mod to install by installing it from the steam workshop, apparently it adds to `mods.json` with double backslashes since it's windows, the end result is:


    "mods": [
        "node_modules\\screepsmod-auth\\index.js"
    ],
However I am still not able to push to my private server, receiving the same error you did.

@Hekman - What needs inserted into `mods.json`? I tried the following:

* Open terminal (Windows) in the `server/` directory
* Run `npm install screepsmod-auth` (this placed screepsmod-auth into `server/node_modules`

Looking at `mods.json` the `"mods":[]` section is completely empty. Some of the documentation says that since the `package.json` of `screepsmod-auth` contains `screeps_mod: true` then it should add itself to `mods.json` automatically.

**Comment by FENG-MASTER** [comment]
+1

**Comment by stfn-c** [comment]
+1

**Comment by linker-err0r** [comment]
Why is it we have to install a third party mod to connect to the built in server? Seems like an extra hassle for no reason.
